### ISSUE TITLE
[BUG]Module Axios not found.

### ISSUE THREAD

**Issue by KelsonCarmozine** [ZupIT/ritchie-cli#149]
**What happened**:
When I create a formula in node using module Axios the execution result in not found the module.

**What you expected to happen**:
The execution occur normally.

**How to reproduce it (as minimally and precisely as possible)**:
Create a formula using node and the module Axios and execute it.

**Anything else we need to know?**:
I test the code and it work normally.
I new in the open source community, if it isn't the correct local to post this I am sorry. 
I opened a other bug issue that is close but the problem wasn't resolve, I don't know if the correct is open a new issue but I comment in that issue after it close. Please check it https://github.com/ZupIT/ritchie-cli/issues/148

**Environment**:
Ritchie version (use rit --version): rit version 1.0.0-beta.13 (single)
Operating System: Linux - Ubunto

**Comment by kaduartur** [comment]
Hello KelsonCarmozine, we really have a bug. In the next release, this will be fixed. This is because the **run_template** file is not running npm install. To fix it add the npm install before the node index.js

![carbon (1)](https://user-images.githubusercontent.com/17505818/84042854-fd105900-a97b-11ea-9fb8-0559f6a394ec.png)
