### ISSUE TITLE
[FEATURE] Allow running any language

### ISSUE THREAD

**Issue by viniciusramosdefaria** [ZupIT/ritchie-cli#19]
### What would you like to be added:

Allow running formulas inside a workspace, like the following image:

![image](https://user-images.githubusercontent.com/20795151/79149115-01196380-7d9d-11ea-9b3a-9638d0dd44df.png)

### Why is this needed:

 To increase the amount of languages supported by ritchie.

**Comment by fghso** [comment]
Have you considered running the formulas inside containers? Wouldn't that allow to run a formula in any language, even without generating the binaries? Each container would only have to provide the correct environment for the language it supports. Or you could have a single container with all environments configured. Or even have one container per formula. In any case, the point is not to depend on the host machine to execute the formulas, like what many companies are already doing for applications. Is that on your roadmap?

**Comment by viniciusramosdefaria** [comment]
At first we considered only supporting running your formulas on a controlled environment (like you can achieve by using containers). I agree that it would be really flexible to allow running formulas inside containers, but our first users (mainly financial companies) were really strict regarding what the user could run on their machines, so we gave up on the idea.
We can open a new issue to tackle the scenario you described.
Talking about the docker images, it would be really cool to allow users to use already configured environments to speed up formula development and delivery.
It wasn't on our roadmap, but now it is :)

**Comment by fghso** [comment]
Hi @viniciusramosdefaria! Thanks for the explanation, makes total sense. I heard about Ritchie today at TDC Online and it seems very promising! I'm going to test it as soon as I can. I've asked about containers because we use Docker for Python and JS projects here at the company. Therefore, containers would be a great way for us to develop and execute formulas on any machine, regardless of platform and OS. Congrats for all good work!
