### ISSUE TITLE
[BUG] Create formula with specific words

### ISSUE THREAD

**Issue by victor-schumacher** [ZupIT/ritchie-cli#249]
**What happened**:

Error after create formula with specific words like:
go
java
python
test
formula
form

**What you expected to happen**:
Be warned about unallowed words

**How to reproduce it (as minimally and precisely as possible)**:
rit create formula
enter the new command like: rit go go 
and choose go language

errors came while building formula:

Build error: 
main.go:5:2: 
pkg/go/go.go:1:9: expected 'IDENT', found 'go'
pkg/go/go.go:3:1: expected ';', found 'import'
make: *** [Makefile:19: build] Error 1

**Environment**:
- Ritchie version: Building master
- Operating System: Linux Ubuntu 20.04

**Comment by brunasilvazup** [comment]
Hello,

Before the updates I decided to check if the error persists:

I ran the following commands in version 2.x, version 1.x legacy:

``` bash
rit go demo
rit java demo
rit python demo
rit test demo
rit formula demo
rit form demo
```

So, I tested all the mentioned cases and the formulas work normally.
I will close this issue because the bug is not occurring, both in the legacy version and in the new one.


If the error recurs, please open a new issue with more information.
Thank you for your contribution.
